[15-May-21 13:24:24] [Scholapp server] [Process: 4869] [Scholapp] - INFO - Setting up flask_microservices.audio_microservice.audio_app
[15-May-21 13:24:24] [Scholapp server] [Process: 4869] [Scholapp] - INFO - Setting up was successful
[15-May-21 13:24:32] [Scholapp server] [Process: 4869] [Scholapp] - INFO - Creating: /home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/audio_microservice/static/00003
[15-May-21 13:24:32] [Scholapp server] [Process: 4869] [Scholapp] - INFO - Creating: /home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/audio_microservice/static/00003/idan57
[15-May-21 13:24:38] [Scholapp server] [Process: 4869] [Scholapp] - INFO - Deleting: /home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/audio_microservice/static/00003/idan57
[15-May-21 13:24:38] [Scholapp server] [Process: 4869] [Scholapp] - ERROR - Traceback (most recent call last):
  File "/home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/audio_microservice/audio_app.py", line 53, in del_audio_path
    self._audios[class_id][username].rmdir()
  File "/usr/lib/python3.8/pathlib.py", line 1332, in rmdir
    self._accessor.rmdir(self)
FileNotFoundError: [Errno 2] No such file or directory: '/home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/audio_microservice/static/00003/idan57'

