[08-May-21 22:26:04] [Scholapp server] [Process: 6852] [Scholapp] - INFO - Setting up flask_microservices.test_microservice.test_app
[08-May-21 22:26:05] [Scholapp server] [Process: 6852] [Scholapp] - INFO - Deserializing tests
[08-May-21 22:26:05] [Scholapp server] [Process: 6852] [Scholapp] - INFO - Setting up was successful
[08-May-21 22:27:48] [Scholapp server] [Process: 6852] [Scholapp] - ERROR - Traceback (most recent call last):
  File "/home/idan/Desktop/final_proj/Final-Project-Server/utilities/decorators/in_try_catch.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/test_microservice/test_app.py", line 382, in actual_add_test
    self._test_container.add_test(Test().from_json(flask.request.get_json()))
  File "/home/idan/Desktop/final_proj/Final-Project-Server/server/test_manager/data_containers/test.py", line 178, in from_json
    self._classroom = json.loads(json_val["classroom"])
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

